### ISSUE TITLE
Clarify in wiki that G33 does several iterations

### ISSUE THREAD

**Issue by whudson** [aegean-odyssey/mpmd_marlin_1.1.x#12]
I was following the Wiki for calibration, and when running the AUTO_CALIBRATE.gcode I thought something was wrong at first as I did not expect it to repeat so many times. Could you add a note to the documentation that this is normal for the auto-calibration to "loop" several times and it takes a while to complete?

**Comment by aegean-odyssey** [comment]
Good point. I've added a note in the [wiki](https://github.com/aegean-odyssey/mpmd_marlin_1.1.x/wiki/Calibrating-the-Printer). Thank you for giving the firmware a try -- and for reading the docs!
