### ISSUE TITLE
E stepper motor 

### ISSUE THREAD

**Issue by awk2019** [aegean-odyssey/mpmd_marlin_1.1.x#2]
my E stepper motor dose not work just clunks and hums 
119r08
mpmd_marlin_1.1.x-119r08-SM0000-ACfan-05Alimit.bin
and 
mpmd_marlin_1.1.x-119r08-SM0001-ACfan-05Alimit.bin

**Comment by aegean-odyssey** [comment]
Please, tell me more. Is the issue resolved? How? This is not an issue we've seen. Most interested in tracking down any problems. Thank you.

**Comment by awk2019** [comment]
Was my fault, forgot to preheat extruder be for testing my motor directions.

**Comment by aegean-odyssey** [comment]
Good to hear that your issue is resolved. Thank you for giving the firmware a try.
