### ISSUE TITLE
Printer hangs after G29 error

### ISSUE THREAD

**Issue by ToxicFrog** [aegean-odyssey/mpmd_marlin_1.1.x#28]
It looks like the firmware has some checking for completely ridiculous G29 results caused by one of the switches getting stuck down and/or the switches being so finely balanced that just moving the print head around closes them, and will abort the G29 procedure if it detects this. When that happens, the LCD will show an error message and the indicator LED will flash red. Pressing the button on the front panel will return the LCD to normal operation, but the LED keeps flashing red and the printer won't respond to serial commands until you power cycle it. Since I'm calibrating it via serial rather than using the gcode files on the SD, this is annoying.

**Comment by aegean-odyssey** [comment]
Please bear with me. I'm going to close this issue, and take up your comment in the context of the discussion into  issue #27. You've touch on a broader issue here.
