### ISSUE TITLE
Version clarification

### ISSUE THREAD

**Issue by BackwardEcho** [aegean-odyssey/mpmd_marlin_1.1.x#79]
Just came to mind that it should be mentioned somewhere on the description that the firmware is for the V1 MPMD and not the recently released V2.

**Comment by aegean-odyssey** [comment]
Agreed. A clarification of sorts that should probably show up in the project's description, the FAQ, and in a few other places in the WIKI documentation.  I'll get on it.

**Comment by aegean-odyssey** [comment]
Readme, WIKI, and Release pages updated.
