### ISSUE TITLE
Firmware will not flash from newer cards which the new firmware will read just fine

### ISSUE THREAD

**Issue by nathanielstenzel** [aegean-odyssey/mpmd_marlin_1.1.x#83]
Just a heads up in case it was not known. People may want to keep their old microSD card on hand for flashing. A microSD card that the new firmware will read may not be good for flashing. The flashing is most likely done by the ESPxx in the control panel.

While flashing from one of your versions to another one of your versions, it would not flash. I had to put the required files on the old microSD card.

This may have already been covered elsewhere, but the quickstart does not look like it hints at this. Maybe it would be a good thing to mention there.

**Comment by aegean-odyssey** [comment]
Yes, the bootloader can be finicky about which micro SD cards and formats it will recognize. Often it's a matter of formatting the card "just" right, though the information and user experience are mixed on what "just" right is. Even then, some cards just don't work. I've one Amazon-branded 4GB card that works for printing, but not at all for installing the firmware. Other cards here with capacities from 1GB to 16GB work without a problem.

There is some information in the wiki page, [Installing the Firmware](https://github.com/aegean-odyssey/mpmd_marlin_1.1.x/wiki/Installing-the-Firmware), but there's no difinitive answer about what cards will work and what cards won't.

Good thought to hang on to the card that comes with the printer. Please feel free to add a note in the quick start and/or firmware installation pages of the wiki.

**Comment by nathanielstenzel** [comment]
![image](https://user-images.githubusercontent.com/9649344/131026940-de812c71-a946-486e-a3e4-b438f32a4452.png)
I added the "if the firmware did not flash...refer to [micro SD card] or use the original microSD card because the bootloader is picky" part. I think it might be a good idea to add a quick note in [micro SD card] to suggest they keep the original card.

**Comment by aegean-odyssey** [comment]
Yes, probably should update the notes on the SD card before the next release. Reopening as a reminder.
